In [1]:
import pandas as pd
from spicy import stats

In [2]:
dataset_path = './datasets/consolidated/consolidated.csv'

data = pd.read_csv(
    filepath_or_buffer=dataset_path,
)

data['date'] = pd.to_datetime(data['date']).dt.date

data.drop(columns=['date'], inplace=True)

data

      positive   neutral  negative    open    high     low  volume   close
0     0.224461  0.501282  0.274257    15.7    17.0    15.6   61502    16.9
1     0.288634  0.496198  0.215168    16.8    17.6    16.6   60975    17.4
2     0.257223  0.437274  0.305503    17.3    17.6    16.8   49439    17.9
3     0.235050  0.551573  0.213377    17.5    19.2    15.6  172009    17.8
4     0.231190  0.506552  0.262257    16.9    17.8    15.4   80767    18.7
...        ...       ...       ...     ...     ...     ...     ...     ...
2531  0.226849  0.446411  0.326740  7210.8  7293.8  7128.5  718074  7261.8
2532  0.169157  0.471205  0.359638  7261.9  7375.9  7256.5  610964  7196.4
2533  0.197365  0.523340  0.279295  7321.6  7518.9  7303.0  611687  7199.8
2534  0.170356  0.481577  0.348067  7397.5  7420.9  7244.1  606110  6967.0
2535  0.198009  0.451574  0.350417  7261.5  7331.0  7167.4  586595  7343.1

[2536 rows x 8 columns]

In [3]:
# Iterar sobre las columnas y realizar la prueba de Anderson-Darling
for columna in data.columns:
    resultado = stats.anderson(data[columna])

    # Obtener el valor crítico y estadístico
    estadistica = resultado.statistic
    valor_critico = resultado.critical_values[2]  # Nivel de significancia del 5% (índice 2)

    # Imprimir los resultados para cada columna
    print(f"Columna: {columna}")
    print(f"Nivel de significancia: 0.05")
    print(f"Valor crítico: {valor_critico}")
    print(f"Estadística de prueba: {round(estadistica, 4)}")

    # Comparación con el valor crítico correspondiente al nivel de significancia
    if estadistica > valor_critico:
        print("Se rechaza la hipótesis nula: los datos no siguen una distribución normal")
    else:
        print("No se rechaza la hipótesis nula: los datos podrían seguir una distribución normal")
    print()

Columna: positive
Nivel de significancia: 0.05
Valor crítico: 0.786
Estadística de prueba: 44.1749
Se rechaza la hipótesis nula: los datos no siguen una distribución normal

Columna: neutral
Nivel de significancia: 0.05
Valor crítico: 0.786
Estadística de prueba: 0.7598
No se rechaza la hipótesis nula: los datos podrían seguir una distribución normal

Columna: negative
Nivel de significancia: 0.05
Valor crítico: 0.786
Estadística de prueba: 24.375
Se rechaza la hipótesis nula: los datos no siguen una distribución normal

Columna: open
Nivel de significancia: 0.05
Valor crítico: 0.786
Estadística de prueba: 253.8658
Se rechaza la hipótesis nula: los datos no siguen una distribución normal

Columna: high
Nivel de significancia: 0.05
Valor crítico: 0.786
Estadística de prueba: 252.8056
Se rechaza la hipótesis nula: los datos no siguen una distribución normal

Columna: low
Nivel de significancia: 0.05
Valor crítico: 0.786
Estadística de prueba: 255.6721
Se rechaza la hipótesis nula: los datos no siguen una distribución normal

Columna: volume
Nivel de significancia: 0.05
Valor crítico: 0.786
Estadística de prueba: 579.8344
Se rechaza la hipótesis nula: los datos no siguen una distribución normal

Columna: close
Nivel de significancia: 0.05
Valor crítico: 0.786
Estadística de prueba: 252.4325
Se rechaza la hipótesis nula: los datos no siguen una distribución normal

In [4]:
transformer_rmse = (
  0.005927,
  0.004217,
  0.017937,
  0.042225,
  0.052780,
)

lstm_rmse = (
  0.008857,
  0.003395,
  0.003394,
  0.156953,
  0.072873,
)

gru_rmse = (
  0.024235,
  0.010124,
  0.018131,
  0.269992,
  0.172274,
)

In [6]:
stats.friedmanchisquare(transformer_rmse, lstm_rmse, gru_rmse)

FriedmanchisquareResult(statistic=7.6000000000000085, pvalue=0.0223707718561655)

In [5]:
transformer_mape = (
  0.107872,
  0.071275,
  0.057524,
  0.020288,
  0.029633,
)

lstm_mape = (
  0.099008,
  0.041344,
  0.024398,
  0.138263,
  0.045839,
)

gru_mape = (
  0.163996,
  0.044858,
  0.034060,
  0.025575,
  0.062061,
)

In [7]:
stats.friedmanchisquare(transformer_mape, lstm_mape, gru_mape)

FriedmanchisquareResult(statistic=1.6000000000000014, pvalue=0.44932896411722134)